# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'

fs_permissions = [{ access = "read-write", path = "./tmp"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
rootstock = "${ROOTSTOCK_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
local = "${LOCAL_RPC_URL}"

[etherscan]
#mainnet = { key = "${ETHERSCAN_API_KEY}" }
#goerli = { key = "${ETHERSCAN_API_KEY}" }
#sepolia = { key = "${ETHERSCAN_API_KEY}" }